Minor: Expected is Equal's first argument
When the test fails, something like this is displayed for L25:
FAIL: TestMakeHashOfOperationBodyPayment (0.00s)
    require.go:157:
            Error Trace:    operation_test.go:28
            Error:          Not equal:
                            expected: 5khwjo7zt1zY1wV15neGY1TPY5YPQrJrNeJoyEKGPUa9
                            actual  : GodiXQkWvAAbobhLBnWK8QS8aArb1ZoR2Ms8JswYUvL3
As seen here, expected and actual are reversed.